import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:intermittent_fasting/services/storage_service.dart';
import 'package:intermittent_fasting/services/health_service.dart';
import 'package:intermittent_fasting/services/notification_service.dart';
import 'package:intermittent_fasting/services/ai_coach_service.dart';
import 'package:intermittent_fasting/services/food_db_service.dart';
import 'package:intermittent_fasting/presenters/stats_presenter.dart';
import 'package:intermittent_fasting/presenters/fasting_presenter.dart';
import 'package:intermittent_fasting/presenters/activity_presenter.dart';
import 'package:intermittent_fasting/presenters/quest_presenter.dart';
import 'package:intermittent_fasting/presenters/hub_presenter.dart';
import 'package:intermittent_fasting/presenters/settings_presenter.dart';
import 'package:intermittent_fasting/presenters/nutrition_presenter.dart';
import 'package:intermittent_fasting/presenters/treasury_dashboard_presenter.dart';
import 'package:intermittent_fasting/presenters/bills_receivables_presenter.dart';

// All mocks are NiceMocks: unstubbed methods return sensible dummies instead of
// throwing MissingStubError. The strict @GenerateMocks output was generated by
// mockito 5.4.6 (which emitted a missing-stub fallback for value-returning
// methods); mockito >=5.5 dropped that, so regenerating strict mocks broke the
// finance suites. NiceMocks restore the lenient behavior the tests rely on and
// keep `build_runner` output reproducible across mockito versions.
@GenerateNiceMocks([
  MockSpec<StorageService>(),
  MockSpec<HealthService>(),
  MockSpec<NotificationService>(),
  MockSpec<AiCoachService>(),
  MockSpec<FoodDbService>(),
  MockSpec<StatsPresenter>(),
  MockSpec<FastingPresenter>(),
  MockSpec<ActivityPresenter>(),
  MockSpec<QuestPresenter>(),
  MockSpec<HubPresenter>(),
  MockSpec<SettingsPresenter>(),
  MockSpec<NutritionPresenter>(),
  MockSpec<TreasuryDashboardPresenter>(),
  MockSpec<BillsReceivablesPresenter>(),
])
void main() {}
