// Mocks generated by Mockito 5.4.6 from annotations
// in intermittent_fasting/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i30;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i7;
import 'package:intermittent_fasting/models/activity_goals.dart' as _i6;
import 'package:intermittent_fasting/models/activity_log.dart' as _i5;
import 'package:intermittent_fasting/models/ai_meal_estimate.dart' as _i8;
import 'package:intermittent_fasting/models/daily_nutrition_log.dart' as _i3;
import 'package:intermittent_fasting/models/fasting_log.dart' as _i11;
import 'package:intermittent_fasting/models/finance/bill.dart' as _i20;
import 'package:intermittent_fasting/models/finance/budget.dart' as _i18;
import 'package:intermittent_fasting/models/finance/budgeted_expense.dart'
    as _i19;
import 'package:intermittent_fasting/models/finance/finance_category.dart'
    as _i17;
import 'package:intermittent_fasting/models/finance/financial_account.dart'
    as _i15;
import 'package:intermittent_fasting/models/finance/monthly_summary.dart'
    as _i22;
import 'package:intermittent_fasting/models/finance/receivable.dart' as _i21;
import 'package:intermittent_fasting/models/finance/transaction_record.dart'
    as _i16;
import 'package:intermittent_fasting/models/food_db_entry.dart' as _i28;
import 'package:intermittent_fasting/models/food_template.dart' as _i14;
import 'package:intermittent_fasting/models/nutrition_goals.dart' as _i4;
import 'package:intermittent_fasting/models/quest.dart' as _i12;
import 'package:intermittent_fasting/models/tdee_profile.dart' as _i13;
import 'package:intermittent_fasting/models/user_stats.dart' as _i2;
import 'package:intermittent_fasting/presenters/activity_presenter.dart'
    as _i32;
import 'package:intermittent_fasting/presenters/fasting_presenter.dart' as _i31;
import 'package:intermittent_fasting/presenters/stats_presenter.dart' as _i29;
import 'package:intermittent_fasting/services/ai_estimation_service.dart'
    as _i26;
import 'package:intermittent_fasting/services/food_db_service.dart' as _i27;
import 'package:intermittent_fasting/services/health_service.dart' as _i24;
import 'package:intermittent_fasting/services/notification_service.dart'
    as _i25;
import 'package:intermittent_fasting/services/storage_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserStats_0 extends _i1.SmartFake implements _i2.UserStats {
  _FakeUserStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDailyNutritionLog_1 extends _i1.SmartFake
    implements _i3.DailyNutritionLog {
  _FakeDailyNutritionLog_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNutritionGoals_2 extends _i1.SmartFake
    implements _i4.NutritionGoals {
  _FakeNutritionGoals_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityLog_3 extends _i1.SmartFake implements _i5.ActivityLog {
  _FakeActivityLog_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityGoals_4 extends _i1.SmartFake implements _i6.ActivityGoals {
  _FakeActivityGoals_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterLocalNotificationsPlugin_5 extends _i1.SmartFake
    implements _i7.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAiMealEstimate_6 extends _i1.SmartFake
    implements _i8.AiMealEstimate {
  _FakeAiMealEstimate_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i9.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> saveUserStats(_i2.UserStats? stats) => (super.noSuchMethod(
        Invocation.method(
          #saveUserStats,
          [stats],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i2.UserStats> loadUserStats() => (super.noSuchMethod(
        Invocation.method(
          #loadUserStats,
          [],
        ),
        returnValue: _i10.Future<_i2.UserStats>.value(_FakeUserStats_0(
          this,
          Invocation.method(
            #loadUserStats,
            [],
          ),
        )),
      ) as _i10.Future<_i2.UserStats>);

  @override
  _i10.Future<void> saveState({
    required bool? isFasting,
    DateTime? startTime,
    DateTime? eatingStartTime,
    required int? elapsedSeconds,
    required int? fastingGoalHours,
    required List<_i11.FastingLog>? history,
    required List<_i12.Quest>? quests,
    DateTime? lastPenaltyCheckDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveState,
          [],
          {
            #isFasting: isFasting,
            #startTime: startTime,
            #eatingStartTime: eatingStartTime,
            #elapsedSeconds: elapsedSeconds,
            #fastingGoalHours: fastingGoalHours,
            #history: history,
            #quests: quests,
            #lastPenaltyCheckDate: lastPenaltyCheckDate,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>> loadState() => (super.noSuchMethod(
        Invocation.method(
          #loadState,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<void> saveNutritionLog(_i3.DailyNutritionLog? log) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveNutritionLog,
          [log],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.DailyNutritionLog> loadTodayNutritionLog() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadTodayNutritionLog,
          [],
        ),
        returnValue:
            _i10.Future<_i3.DailyNutritionLog>.value(_FakeDailyNutritionLog_1(
          this,
          Invocation.method(
            #loadTodayNutritionLog,
            [],
          ),
        )),
      ) as _i10.Future<_i3.DailyNutritionLog>);

  @override
  _i10.Future<List<_i3.DailyNutritionLog>> loadNutritionHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadNutritionHistory,
          [],
        ),
        returnValue: _i10.Future<List<_i3.DailyNutritionLog>>.value(
            <_i3.DailyNutritionLog>[]),
      ) as _i10.Future<List<_i3.DailyNutritionLog>>);

  @override
  _i10.Future<void> saveNutritionGoals(_i4.NutritionGoals? goals) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveNutritionGoals,
          [goals],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i4.NutritionGoals> loadNutritionGoals() => (super.noSuchMethod(
        Invocation.method(
          #loadNutritionGoals,
          [],
        ),
        returnValue:
            _i10.Future<_i4.NutritionGoals>.value(_FakeNutritionGoals_2(
          this,
          Invocation.method(
            #loadNutritionGoals,
            [],
          ),
        )),
      ) as _i10.Future<_i4.NutritionGoals>);

  @override
  _i10.Future<void> saveNutritionStreak(int? streak) => (super.noSuchMethod(
        Invocation.method(
          #saveNutritionStreak,
          [streak],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> loadNutritionStreak() => (super.noSuchMethod(
        Invocation.method(
          #loadNutritionStreak,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> saveNutritionGoalMetDate(String? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveNutritionGoalMetDate,
          [date],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> loadNutritionGoalMetDate() => (super.noSuchMethod(
        Invocation.method(
          #loadNutritionGoalMetDate,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<void> saveTdeeProfile(_i13.TdeeProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTdeeProfile,
          [profile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i13.TdeeProfile?> loadTdeeProfile() => (super.noSuchMethod(
        Invocation.method(
          #loadTdeeProfile,
          [],
        ),
        returnValue: _i10.Future<_i13.TdeeProfile?>.value(),
      ) as _i10.Future<_i13.TdeeProfile?>);

  @override
  _i10.Future<void> saveFoodLibrary(List<_i14.FoodTemplate>? templates) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFoodLibrary,
          [templates],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i14.FoodTemplate>> loadFoodLibrary() => (super.noSuchMethod(
        Invocation.method(
          #loadFoodLibrary,
          [],
        ),
        returnValue:
            _i10.Future<List<_i14.FoodTemplate>>.value(<_i14.FoodTemplate>[]),
      ) as _i10.Future<List<_i14.FoodTemplate>>);

  @override
  _i10.Future<void> saveLogStreak(int? streak) => (super.noSuchMethod(
        Invocation.method(
          #saveLogStreak,
          [streak],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> loadLogStreak() => (super.noSuchMethod(
        Invocation.method(
          #loadLogStreak,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> saveLogStreakDate(String? date) => (super.noSuchMethod(
        Invocation.method(
          #saveLogStreakDate,
          [date],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> loadLogStreakDate() => (super.noSuchMethod(
        Invocation.method(
          #loadLogStreakDate,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<void> saveActivityLog(_i5.ActivityLog? log) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveActivityLog,
          [log],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i5.ActivityLog> loadTodayActivityLog() => (super.noSuchMethod(
        Invocation.method(
          #loadTodayActivityLog,
          [],
        ),
        returnValue: _i10.Future<_i5.ActivityLog>.value(_FakeActivityLog_3(
          this,
          Invocation.method(
            #loadTodayActivityLog,
            [],
          ),
        )),
      ) as _i10.Future<_i5.ActivityLog>);

  @override
  _i10.Future<List<_i5.ActivityLog>> loadActivityHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadActivityHistory,
          [],
        ),
        returnValue:
            _i10.Future<List<_i5.ActivityLog>>.value(<_i5.ActivityLog>[]),
      ) as _i10.Future<List<_i5.ActivityLog>>);

  @override
  _i10.Future<Set<String>> loadActivityLogKeys() => (super.noSuchMethod(
        Invocation.method(
          #loadActivityLogKeys,
          [],
        ),
        returnValue: _i10.Future<Set<String>>.value(<String>{}),
      ) as _i10.Future<Set<String>>);

  @override
  _i10.Future<void> clearActivityHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearActivityHistory,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveActivityLogs(List<_i5.ActivityLog>? logs) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveActivityLogs,
          [logs],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveActivityGoals(_i6.ActivityGoals? goals) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveActivityGoals,
          [goals],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i6.ActivityGoals> loadActivityGoals() => (super.noSuchMethod(
        Invocation.method(
          #loadActivityGoals,
          [],
        ),
        returnValue: _i10.Future<_i6.ActivityGoals>.value(_FakeActivityGoals_4(
          this,
          Invocation.method(
            #loadActivityGoals,
            [],
          ),
        )),
      ) as _i10.Future<_i6.ActivityGoals>);

  @override
  _i10.Future<String?> loadPreferredStepsSource() => (super.noSuchMethod(
        Invocation.method(
          #loadPreferredStepsSource,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<void> savePreferredStepsSource(String? sourceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePreferredStepsSource,
          [sourceId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveActivityGoalMetDate(String? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveActivityGoalMetDate,
          [date],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> loadActivityGoalMetDate() => (super.noSuchMethod(
        Invocation.method(
          #loadActivityGoalMetDate,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<void> saveActivityStreak(int? streak) => (super.noSuchMethod(
        Invocation.method(
          #saveActivityStreak,
          [streak],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> loadActivityStreak() => (super.noSuchMethod(
        Invocation.method(
          #loadActivityStreak,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> saveAccounts(List<_i15.FinancialAccount>? accounts) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAccounts,
          [accounts],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i15.FinancialAccount>> loadAccounts() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAccounts,
          [],
        ),
        returnValue: _i10.Future<List<_i15.FinancialAccount>>.value(
            <_i15.FinancialAccount>[]),
      ) as _i10.Future<List<_i15.FinancialAccount>>);

  @override
  _i10.Future<void> saveTransactions(
          List<_i16.TransactionRecord>? transactions) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTransactions,
          [transactions],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i16.TransactionRecord>> loadTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadTransactions,
          [],
        ),
        returnValue: _i10.Future<List<_i16.TransactionRecord>>.value(
            <_i16.TransactionRecord>[]),
      ) as _i10.Future<List<_i16.TransactionRecord>>);

  @override
  _i10.Future<void> saveFinanceCategories(
          List<_i17.FinanceCategory>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFinanceCategories,
          [categories],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i17.FinanceCategory>> loadFinanceCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFinanceCategories,
          [],
        ),
        returnValue: _i10.Future<List<_i17.FinanceCategory>>.value(
            <_i17.FinanceCategory>[]),
      ) as _i10.Future<List<_i17.FinanceCategory>>);

  @override
  _i10.Future<void> saveBudgets(List<_i18.Budget>? budgets) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBudgets,
          [budgets],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i18.Budget>> loadBudgets() => (super.noSuchMethod(
        Invocation.method(
          #loadBudgets,
          [],
        ),
        returnValue: _i10.Future<List<_i18.Budget>>.value(<_i18.Budget>[]),
      ) as _i10.Future<List<_i18.Budget>>);

  @override
  _i10.Future<void> saveBudgetedExpenses(
          List<_i19.BudgetedExpense>? expenses) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBudgetedExpenses,
          [expenses],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i19.BudgetedExpense>> loadBudgetedExpenses() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadBudgetedExpenses,
          [],
        ),
        returnValue: _i10.Future<List<_i19.BudgetedExpense>>.value(
            <_i19.BudgetedExpense>[]),
      ) as _i10.Future<List<_i19.BudgetedExpense>>);

  @override
  _i10.Future<void> saveBills(List<_i20.Bill>? bills) => (super.noSuchMethod(
        Invocation.method(
          #saveBills,
          [bills],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i20.Bill>> loadBills() => (super.noSuchMethod(
        Invocation.method(
          #loadBills,
          [],
        ),
        returnValue: _i10.Future<List<_i20.Bill>>.value(<_i20.Bill>[]),
      ) as _i10.Future<List<_i20.Bill>>);

  @override
  _i10.Future<void> saveReceivables(List<_i21.Receivable>? receivables) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveReceivables,
          [receivables],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i21.Receivable>> loadReceivables() => (super.noSuchMethod(
        Invocation.method(
          #loadReceivables,
          [],
        ),
        returnValue:
            _i10.Future<List<_i21.Receivable>>.value(<_i21.Receivable>[]),
      ) as _i10.Future<List<_i21.Receivable>>);

  @override
  _i10.Future<void> saveMonthlySummaries(
          List<_i22.MonthlySummary>? summaries) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMonthlySummaries,
          [summaries],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i22.MonthlySummary>> loadMonthlySummaries() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMonthlySummaries,
          [],
        ),
        returnValue: _i10.Future<List<_i22.MonthlySummary>>.value(
            <_i22.MonthlySummary>[]),
      ) as _i10.Future<List<_i22.MonthlySummary>>);

  @override
  _i10.Future<String> exportAllData() => (super.noSuchMethod(
        Invocation.method(
          #exportAllData,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i23.dummyValue<String>(
          this,
          Invocation.method(
            #exportAllData,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> importAllData(String? jsonString) => (super.noSuchMethod(
        Invocation.method(
          #importAllData,
          [jsonString],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [HealthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthService extends _i1.Mock implements _i24.HealthService {
  MockHealthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> hasPermissions() => (super.noSuchMethod(
        Invocation.method(
          #hasPermissions,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> openHealthConnectSettings() => (super.noSuchMethod(
        Invocation.method(
          #openHealthConnectSettings,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> readTodaySteps({String? sourceId}) => (super.noSuchMethod(
        Invocation.method(
          #readTodaySteps,
          [],
          {#sourceId: sourceId},
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<double?> readTodayActiveCalories({String? sourceId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readTodayActiveCalories,
          [],
          {#sourceId: sourceId},
        ),
        returnValue: _i10.Future<double?>.value(),
      ) as _i10.Future<double?>);

  @override
  _i10.Future<double?> readTodayTotalCalories({String? sourceId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readTodayTotalCalories,
          [],
          {#sourceId: sourceId},
        ),
        returnValue: _i10.Future<double?>.value(),
      ) as _i10.Future<double?>);

  @override
  _i10.Future<double?> readTodayDistance({String? sourceId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readTodayDistance,
          [],
          {#sourceId: sourceId},
        ),
        returnValue: _i10.Future<double?>.value(),
      ) as _i10.Future<double?>);

  @override
  _i10.Future<
      ({
        double? activeCalories,
        double? distance,
        int steps,
        double? totalCalories
      })> readDayData(
    DateTime? date, {
    String? stepsSourceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readDayData,
          [date],
          {#stepsSourceId: stepsSourceId},
        ),
        returnValue: _i10.Future<
            ({
              double? activeCalories,
              double? distance,
              int steps,
              double? totalCalories
            })>.value((
          activeCalories: null,
          distance: null,
          steps: 0,
          totalCalories: null
        )),
      ) as _i10.Future<
          ({
            double? activeCalories,
            double? distance,
            int steps,
            double? totalCalories
          })>);

  @override
  _i10.Future<
      Map<
          String,
          ({
            double? activeCalories,
            double? distance,
            int steps,
            double? totalCalories
          })>> readRangeDataByDay(
    DateTime? start,
    DateTime? end, {
    String? stepsSourceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readRangeDataByDay,
          [
            start,
            end,
          ],
          {#stepsSourceId: stepsSourceId},
        ),
        returnValue: _i10.Future<
            Map<
                String,
                ({
                  double? activeCalories,
                  double? distance,
                  int steps,
                  double? totalCalories
                })>>.value(<String,
            ({
          double? activeCalories,
          double? distance,
          int steps,
          double? totalCalories
        })>{}),
      ) as _i10.Future<
          Map<
              String,
              ({
                double? activeCalories,
                double? distance,
                int steps,
                double? totalCalories
              })>>);

  @override
  _i10.Future<List<({String sourceId, String sourceName})>> readStepSources() =>
      (super.noSuchMethod(
        Invocation.method(
          #readStepSources,
          [],
        ),
        returnValue:
            _i10.Future<List<({String sourceId, String sourceName})>>.value(
                <({String sourceId, String sourceName})>[]),
      ) as _i10.Future<List<({String sourceId, String sourceName})>>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i25.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.FlutterLocalNotificationsPlugin get flutterLocalNotificationsPlugin =>
      (super.noSuchMethod(
        Invocation.getter(#flutterLocalNotificationsPlugin),
        returnValue: _FakeFlutterLocalNotificationsPlugin_5(
          this,
          Invocation.getter(#flutterLocalNotificationsPlugin),
        ),
      ) as _i7.FlutterLocalNotificationsPlugin);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> scheduleFastingAlarm(
    DateTime? startTime,
    int? goalHours,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleFastingAlarm,
          [
            startTime,
            goalHours,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> scheduleEatingAlarm(
    DateTime? eatingStartTime,
    int? goalHours,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleEatingAlarm,
          [
            eatingStartTime,
            goalHours,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> showSimpleNotification({
    String? title = 'Test Notification',
    String? body = 'This is a test notification',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showSimpleNotification,
          [],
          {
            #title: title,
            #body: body,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> testAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #testAllChannels,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> showFastingTimerNotification(DateTime? endTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #showFastingTimerNotification,
          [endTime],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> showEatingTimerNotification(DateTime? endTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #showEatingTimerNotification,
          [endTime],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancelFastingTimerNotification() => (super.noSuchMethod(
        Invocation.method(
          #cancelFastingTimerNotification,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancelEatingTimerNotification() => (super.noSuchMethod(
        Invocation.method(
          #cancelEatingTimerNotification,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> scheduleQuestNotifications(_i12.Quest? quest) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleQuestNotifications,
          [quest],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancelQuestNotifications(_i12.Quest? quest) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelQuestNotifications,
          [quest],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancelFastingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelFastingNotifications,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancelEatingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelEatingNotifications,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancel(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [AiEstimationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiEstimationService extends _i1.Mock
    implements _i26.AiEstimationService {
  MockAiEstimationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isModelAvailable => (super.noSuchMethod(
        Invocation.getter(#isModelAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isDownloading => (super.noSuchMethod(
        Invocation.getter(#isDownloading),
        returnValue: false,
      ) as bool);

  @override
  int get downloadProgress => (super.noSuchMethod(
        Invocation.getter(#downloadProgress),
        returnValue: 0,
      ) as int);

  @override
  String get modelSizeLabel => (super.noSuchMethod(
        Invocation.getter(#modelSizeLabel),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#modelSizeLabel),
        ),
      ) as String);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> downloadModel({void Function(int)? onProgress}) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadModel,
          [],
          {#onProgress: onProgress},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i8.AiMealEstimate> estimate(String? description) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimate,
          [description],
        ),
        returnValue:
            _i10.Future<_i8.AiMealEstimate>.value(_FakeAiMealEstimate_6(
          this,
          Invocation.method(
            #estimate,
            [description],
          ),
        )),
      ) as _i10.Future<_i8.AiMealEstimate>);
}

/// A class which mocks [FoodDbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodDbService extends _i1.Mock implements _i27.FoodDbService {
  MockFoodDbService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i28.FoodDbEntry>> search(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue:
            _i10.Future<List<_i28.FoodDbEntry>>.value(<_i28.FoodDbEntry>[]),
      ) as _i10.Future<List<_i28.FoodDbEntry>>);

  @override
  _i10.Future<_i28.FoodDbEntry?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i10.Future<_i28.FoodDbEntry?>.value(),
      ) as _i10.Future<_i28.FoodDbEntry?>);
}

/// A class which mocks [StatsPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsPresenter extends _i1.Mock implements _i29.StatsPresenter {
  MockStatsPresenter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get showLevelUpDialog => (super.noSuchMethod(
        Invocation.getter(#showLevelUpDialog),
        returnValue: false,
      ) as bool);

  @override
  _i2.UserStats get stats => (super.noSuchMethod(
        Invocation.getter(#stats),
        returnValue: _FakeUserStats_0(
          this,
          Invocation.getter(#stats),
        ),
      ) as _i2.UserStats);

  @override
  int get maxHp => (super.noSuchMethod(
        Invocation.getter(#maxHp),
        returnValue: 0,
      ) as int);

  @override
  int get nextLevelXp => (super.noSuchMethod(
        Invocation.getter(#nextLevelXp),
        returnValue: 0,
      ) as int);

  @override
  String get rank => (super.noSuchMethod(
        Invocation.getter(#rank),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#rank),
        ),
      ) as String);

  @override
  String get jobTitle => (super.noSuchMethod(
        Invocation.getter(#jobTitle),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#jobTitle),
        ),
      ) as String);

  @override
  set showLevelUpDialog(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #showLevelUpDialog,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> loadStats() => (super.noSuchMethod(
        Invocation.method(
          #loadStats,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void dismissLevelUp() => super.noSuchMethod(
        Invocation.method(
          #dismissLevelUp,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> updateName(String? newName) => (super.noSuchMethod(
        Invocation.method(
          #updateName,
          [newName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addXp(int? amount) => (super.noSuchMethod(
        Invocation.method(
          #addXp,
          [amount],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> modifyHp(int? amount) => (super.noSuchMethod(
        Invocation.method(
          #modifyHp,
          [amount],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> allocatePoint(String? stat) => (super.noSuchMethod(
        Invocation.method(
          #allocatePoint,
          [stat],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> incrementStreak() => (super.noSuchMethod(
        Invocation.method(
          #incrementStreak,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> resetStreak() => (super.noSuchMethod(
        Invocation.method(
          #resetStreak,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> awardStat(String? stat) => (super.noSuchMethod(
        Invocation.method(
          #awardStat,
          [stat],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addListener(_i30.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i30.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FastingPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockFastingPresenter extends _i1.Mock implements _i31.FastingPresenter {
  MockFastingPresenter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isFasting => (super.noSuchMethod(
        Invocation.getter(#isFasting),
        returnValue: false,
      ) as bool);

  @override
  int get elapsedSeconds => (super.noSuchMethod(
        Invocation.getter(#elapsedSeconds),
        returnValue: 0,
      ) as int);

  @override
  int get fastingGoalHours => (super.noSuchMethod(
        Invocation.getter(#fastingGoalHours),
        returnValue: 0,
      ) as int);

  @override
  List<_i11.FastingLog> get history => (super.noSuchMethod(
        Invocation.getter(#history),
        returnValue: <_i11.FastingLog>[],
      ) as List<_i11.FastingLog>);

  @override
  List<_i12.Quest> get quests => (super.noSuchMethod(
        Invocation.getter(#quests),
        returnValue: <_i12.Quest>[],
      ) as List<_i12.Quest>);

  @override
  set isFasting(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isFasting,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set startTime(DateTime? value) => super.noSuchMethod(
        Invocation.setter(
          #startTime,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set eatingStartTime(DateTime? value) => super.noSuchMethod(
        Invocation.setter(
          #eatingStartTime,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set elapsedSeconds(int? value) => super.noSuchMethod(
        Invocation.setter(
          #elapsedSeconds,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set fastingGoalHours(int? value) => super.noSuchMethod(
        Invocation.setter(
          #fastingGoalHours,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set history(List<_i11.FastingLog>? value) => super.noSuchMethod(
        Invocation.setter(
          #history,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set quests(List<_i12.Quest>? value) => super.noSuchMethod(
        Invocation.setter(
          #quests,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastPenaltyCheckDate(DateTime? value) => super.noSuchMethod(
        Invocation.setter(
          #lastPenaltyCheckDate,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> loadState() => (super.noSuchMethod(
        Invocation.method(
          #loadState,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveState() => (super.noSuchMethod(
        Invocation.method(
          #saveState,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> startFast() => (super.noSuchMethod(
        Invocation.method(
          #startFast,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<(int, int)> stopFast() => (super.noSuchMethod(
        Invocation.method(
          #stopFast,
          [],
        ),
        returnValue: _i10.Future<(int, int)>.value((0, 0)),
      ) as _i10.Future<(int, int)>);

  @override
  _i10.Future<void> updateFastingGoal(int? hours) => (super.noSuchMethod(
        Invocation.method(
          #updateFastingGoal,
          [hours],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addQuest(
    String? title,
    int? hour,
    int? minute,
    List<bool>? days, {
    bool? isOneTime = false,
    int? reminderMinutes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQuest,
          [
            title,
            hour,
            minute,
            days,
          ],
          {
            #isOneTime: isOneTime,
            #reminderMinutes: reminderMinutes,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> toggleQuest(
    int? index,
    bool? isEnabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleQuest,
          [
            index,
            isEnabled,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteQuest(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteQuest,
          [index],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateQuest(
    int? index,
    String? title,
    int? hour,
    int? minute,
    List<bool>? days, {
    bool? isOneTime = false,
    int? reminderMinutes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuest,
          [
            index,
            title,
            hour,
            minute,
            days,
          ],
          {
            #isOneTime: isOneTime,
            #reminderMinutes: reminderMinutes,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> completeQuest(
    int? index, {
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeQuest,
          [index],
          {#date: date},
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> testNotification() => (super.noSuchMethod(
        Invocation.method(
          #testNotification,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addTestData() => (super.noSuchMethod(
        Invocation.method(
          #addTestData,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateLog(
    int? index,
    _i11.FastingLog? newLog,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLog,
          [
            index,
            newLog,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteLog(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteLog,
          [index],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> skipEatingWindow() => (super.noSuchMethod(
        Invocation.method(
          #skipEatingWindow,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateStartTime(DateTime? newStartTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStartTime,
          [newStartTime],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateEatingStartTime(DateTime? newStartTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEatingStartTime,
          [newStartTime],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> exportData() => (super.noSuchMethod(
        Invocation.method(
          #exportData,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i23.dummyValue<String>(
          this,
          Invocation.method(
            #exportData,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> importData(String? jsonString) => (super.noSuchMethod(
        Invocation.method(
          #importData,
          [jsonString],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i30.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i30.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ActivityPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityPresenter extends _i1.Mock implements _i32.ActivityPresenter {
  MockActivityPresenter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ActivityLog get todayLog => (super.noSuchMethod(
        Invocation.getter(#todayLog),
        returnValue: _FakeActivityLog_3(
          this,
          Invocation.getter(#todayLog),
        ),
      ) as _i5.ActivityLog);

  @override
  _i6.ActivityGoals get goals => (super.noSuchMethod(
        Invocation.getter(#goals),
        returnValue: _FakeActivityGoals_4(
          this,
          Invocation.getter(#goals),
        ),
      ) as _i6.ActivityGoals);

  @override
  List<_i5.ActivityLog> get history => (super.noSuchMethod(
        Invocation.getter(#history),
        returnValue: <_i5.ActivityLog>[],
      ) as List<_i5.ActivityLog>);

  @override
  bool get isHealthConnectAvailable => (super.noSuchMethod(
        Invocation.getter(#isHealthConnectAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get hasHealthPermission => (super.noSuchMethod(
        Invocation.getter(#hasHealthPermission),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isBackfilling => (super.noSuchMethod(
        Invocation.getter(#isBackfilling),
        returnValue: false,
      ) as bool);

  @override
  bool get isConnecting => (super.noSuchMethod(
        Invocation.getter(#isConnecting),
        returnValue: false,
      ) as bool);

  @override
  bool get healthPermissionDenied => (super.noSuchMethod(
        Invocation.getter(#healthPermissionDenied),
        returnValue: false,
      ) as bool);

  @override
  List<({String sourceId, String sourceName})> get stepSources =>
      (super.noSuchMethod(
        Invocation.getter(#stepSources),
        returnValue: <({String sourceId, String sourceName})>[],
      ) as List<({String sourceId, String sourceName})>);

  @override
  int get todaySteps => (super.noSuchMethod(
        Invocation.getter(#todaySteps),
        returnValue: 0,
      ) as int);

  @override
  double get stepProgress => (super.noSuchMethod(
        Invocation.getter(#stepProgress),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isGoalMet => (super.noSuchMethod(
        Invocation.getter(#isGoalMet),
        returnValue: false,
      ) as bool);

  @override
  double get distanceProgress => (super.noSuchMethod(
        Invocation.getter(#distanceProgress),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isDistanceGoalMet => (super.noSuchMethod(
        Invocation.getter(#isDistanceGoalMet),
        returnValue: false,
      ) as bool);

  @override
  String get summaryLabel => (super.noSuchMethod(
        Invocation.getter(#summaryLabel),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#summaryLabel),
        ),
      ) as String);

  @override
  List<_i5.ActivityLog> get weeklyLogs => (super.noSuchMethod(
        Invocation.getter(#weeklyLogs),
        returnValue: <_i5.ActivityLog>[],
      ) as List<_i5.ActivityLog>);

  @override
  int get weeklyMaxSteps => (super.noSuchMethod(
        Invocation.getter(#weeklyMaxSteps),
        returnValue: 0,
      ) as int);

  @override
  Map<String, _i5.ActivityLog> get historyByDate => (super.noSuchMethod(
        Invocation.getter(#historyByDate),
        returnValue: <String, _i5.ActivityLog>{},
      ) as Map<String, _i5.ActivityLog>);

  @override
  String get todayCaloriesLabel => (super.noSuchMethod(
        Invocation.getter(#todayCaloriesLabel),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#todayCaloriesLabel),
        ),
      ) as String);

  @override
  String get hubSubtitle => (super.noSuchMethod(
        Invocation.getter(#hubSubtitle),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#hubSubtitle),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  double? caloriesBurned(_i5.ActivityLog? log) =>
      (super.noSuchMethod(Invocation.method(
        #caloriesBurned,
        [log],
      )) as double?);

  @override
  _i10.Future<void> loadState() => (super.noSuchMethod(
        Invocation.method(
          #loadState,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> syncFromHealthConnect() => (super.noSuchMethod(
        Invocation.method(
          #syncFromHealthConnect,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setManualSteps(int? steps) => (super.noSuchMethod(
        Invocation.method(
          #setManualSteps,
          [steps],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateGoals(_i6.ActivityGoals? goals) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGoals,
          [goals],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> requestHealthPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestHealthPermission,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> openHealthConnectSettings() => (super.noSuchMethod(
        Invocation.method(
          #openHealthConnectSettings,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> recheckPermissions() => (super.noSuchMethod(
        Invocation.method(
          #recheckPermissions,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> loadStepSources() => (super.noSuchMethod(
        Invocation.method(
          #loadStepSources,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setPreferredStepsSource(String? sourceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreferredStepsSource,
          [sourceId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearAndRebackfill() => (super.noSuchMethod(
        Invocation.method(
          #clearAndRebackfill,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> backfillHistory({int? days = 90}) => (super.noSuchMethod(
        Invocation.method(
          #backfillHistory,
          [],
          {#days: days},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addListener(_i30.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i30.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
